version: '3.1'
services:
  task-service:
    build: ./
    image: task-service
    container_name: task-service
    ports:
      - "9090:9090"
    depends_on:
      - task-service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://task-service-db:5432/task_service_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  task-service-db:
    image: postgres:16.3-alpine
    container_name: task-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=task_service_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
