ALTER TABLE TASKS ALTER COLUMN TASK_ID TYPE BIGINT;
ALTER TABLE TASKS ALTER COLUMN ASSIGNEE_ID TYPE BIGINT;
ALTER TABLE TASKS ALTER COLUMN AUTHOR_ID TYPE BIGINT;
ALTER TABLE TASKS ALTER COLUMN EVENT_ID TYPE BIGINT;
