CREATE TABLE IF NOT EXISTS PUBLIC.EPICS
(
	EPIC_ID		BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME		VARCHAR(250) NOT NULL,
	OWNER_ID	BIGINT NOT NULL,
	EVENT_ID    BIGINT NOT NULL,
	DEADLINE	TIMESTAMP WITHOUT TIME ZONE NOT NULL
);